hydra:
  job:
    chdir: False

train:
  task: "distribution-modelling"
  dataset_name: "roszcz/ecg-segmentation-ltafdb" # huggingface dataset
  batch_size: 128
  num_workers: 8
  lr: 3e-4
  weight_decay: 0.01
  num_epochs: 1
  device: "cuda"
  precision: "16-mixed"
  overfit_batches: 0

paths:
  save_ckpt_dir: "checkpoints" # directory where checkpoints will be saved
  load_ckpt_path: null # if not None, specifies path to model state dict which will be loaded
  log_dir: "logs"
  hf_repo_id: JasiekKaczmarczyk/ecg-segmentation-unet # repo id to upload model to huggingface

unet:
  in_channels: 2 # image channels
  out_channels: 1
  kernel_size: 7
  dim: 32 # initial number of unet channels (will be multiplied by dim_mults)
  dim_mults: [1, 2, 4]
  num_resnet_groups: 4

logger:
  run_name: distribution-modelling-${now:%Y-%m-%d-%H-%M}
  log_every_n_steps: 50
